// Code generated by scripts/externalaccess/prepare-cloudflared-embed.sh; DO NOT EDIT.

//go:build linux && amd64

package cloudflaredembed

import _ "embed"

//go:embed assets/cloudflared-linux-amd64.zst
var embeddedCloudflared_linux_amd64 []byte

func init() {
	register(Asset{
		Version: "2026.2.0",
		SHA256:  "176746db3be7dc7bd48f3dd287c8930a4645ebb6e6700f883fddda5a4c307c16",
		Zstd:    embeddedCloudflared_linux_amd64,
	})
}
