#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PACKAGE_DIR="${ROOT_DIR}/internal/externalaccess/cloudflaredembed"
ASSET_DIR="${PACKAGE_DIR}/assets"
ALLOW_DOWNLOAD="${CLOUDFLARED_EMBED_ALLOW_DOWNLOAD:-0}"

if ! command -v zstd >/dev/null 2>&1; then
  echo "zstd is required to prepare embedded cloudflared assets" >&2
  exit 1
fi

CLOUDFLARED_VERSION="${CLOUDFLARED_VERSION:-2026.2.0}"
GOOS_VALUE="${1:-${GOOS:-$(go env GOOS)}}"
GOARCH_VALUE="${2:-${GOARCH:-$(go env GOARCH)}}"

asset_name=""
asset_sha256=""
archive_kind=""

case "${GOOS_VALUE}/${GOARCH_VALUE}" in
  linux/amd64)
    asset_name="cloudflared-linux-amd64"
    asset_sha256="176746db3be7dc7bd48f3dd287c8930a4645ebb6e6700f883fddda5a4c307c16"
    archive_kind="raw"
    ;;
  linux/arm64)
    asset_name="cloudflared-linux-arm64"
    asset_sha256="03c5d58e283f521d752dc4436014eb341092edf076eb1095953ab82debe54a8e"
    archive_kind="raw"
    ;;
  darwin/amd64)
    asset_name="cloudflared-darwin-amd64.tgz"
    asset_sha256="685688a260c324eb8d9c9434ca22f0ce4f504fd6acd0706787c4833de8d6eb17"
    archive_kind="targz"
    ;;
  darwin/arm64)
    asset_name="cloudflared-darwin-arm64.tgz"
    asset_sha256="ba99c6f87320236b9f842c3ba4b9526f687560125b7b43a581201579543ca4ff"
    archive_kind="targz"
    ;;
  windows/amd64)
    asset_name="cloudflared-windows-amd64.exe"
    asset_sha256="b3279f2186a1c3c438ad5865e802bbbec26090c5d3fdb4ac1113f1143a94837a"
    archive_kind="raw"
    ;;
  *)
    echo "no embedded cloudflared mapping for ${GOOS_VALUE}/${GOARCH_VALUE}; skipping prepare" >&2
    exit 0
    ;;
esac

generated_go="${PACKAGE_DIR}/cloudflared_${GOOS_VALUE}_${GOARCH_VALUE}_embed.go"
generated_go_tmp="${generated_go}.tmp.$$"
embedded_asset="${ASSET_DIR}/cloudflared-${GOOS_VALUE}-${GOARCH_VALUE}.zst"

if [[ -f "${generated_go}" && -f "${embedded_asset}" ]] && grep -q "Version: \"${CLOUDFLARED_VERSION}\"" "${generated_go}"; then
  echo "embedded cloudflared already prepared for ${GOOS_VALUE}/${GOARCH_VALUE}"
  exit 0
fi

if [[ "${ALLOW_DOWNLOAD}" != "1" ]]; then
  cat >&2 <<EOF
embedded cloudflared asset missing or outdated for ${GOOS_VALUE}/${GOARCH_VALUE}
repo-managed assets are required by default
run: bash scripts/externalaccess/update-cloudflared-embed.sh
EOF
  exit 1
fi

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "${tmp_dir}"
  rm -f "${generated_go_tmp}"
}
trap cleanup EXIT

download_path="${tmp_dir}/${asset_name}"
asset_url="https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/${asset_name}"

echo "downloading cloudflared ${CLOUDFLARED_VERSION} for ${GOOS_VALUE}/${GOARCH_VALUE}" >&2
curl -fsSL "${asset_url}" -o "${download_path}"

checksum_cmd="sha256sum"
if ! command -v "${checksum_cmd}" >/dev/null 2>&1; then
  checksum_cmd="shasum -a 256"
fi
download_sha256="$(${checksum_cmd} "${download_path}" | awk '{print $1}')"
if [[ "${download_sha256}" != "${asset_sha256}" ]]; then
  echo "cloudflared download checksum mismatch: got ${download_sha256}, want ${asset_sha256}" >&2
  exit 1
fi

normalized_binary="${tmp_dir}/normalized-$(basename "${asset_name}" .tgz)"
case "${archive_kind}" in
  raw)
    cp "${download_path}" "${normalized_binary}"
    ;;
  targz)
    extract_dir="${tmp_dir}/extract"
    mkdir -p "${extract_dir}"
    tar -xzf "${download_path}" -C "${extract_dir}"
    candidate="$(find "${extract_dir}" -type f \( -name 'cloudflared' -o -name 'cloudflared.exe' \) | head -n 1)"
    if [[ -z "${candidate}" ]]; then
      echo "unable to locate cloudflared binary inside ${asset_name}" >&2
      exit 1
    fi
    cp "${candidate}" "${normalized_binary}"
    ;;
esac

chmod +x "${normalized_binary}"
binary_sha256="$(${checksum_cmd} "${normalized_binary}" | awk '{print $1}')"

mkdir -p "${ASSET_DIR}"
zstd -19 -q -c "${normalized_binary}" > "${embedded_asset}"

cat > "${generated_go_tmp}" <<EOF
// Code generated by scripts/externalaccess/prepare-cloudflared-embed.sh; DO NOT EDIT.

//go:build ${GOOS_VALUE} && ${GOARCH_VALUE}

package cloudflaredembed

import _ "embed"

//go:embed assets/$(basename "${embedded_asset}")
var embeddedCloudflared_${GOOS_VALUE}_${GOARCH_VALUE} []byte

func init() {
	register(Asset{
		Version: "${CLOUDFLARED_VERSION}",
		SHA256:  "${binary_sha256}",
		Zstd:    embeddedCloudflared_${GOOS_VALUE}_${GOARCH_VALUE},
	})
}
EOF

gofmt -w "${generated_go_tmp}"
mv "${generated_go_tmp}" "${generated_go}"
echo "prepared embedded cloudflared for ${GOOS_VALUE}/${GOARCH_VALUE}" >&2
