// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build windows && amd64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-windows-amd64.zst
var embeddedUpgradeShim_windows_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "6e543c34661a8bbe6b7a16654dd41f08825d99d886cae7d772f80567cd4210a4",
		SHA256:       "6753c0af749e22cdc0595c550099b701ec35cf33335cd75303b113722705bd99",
		Zstd:         embeddedUpgradeShim_windows_amd64,
	})
}
