package control

const (
	FeishuCommandWorkspace            = "workspace"
	FeishuCommandWorkspaceList        = "workspace_list"
	FeishuCommandWorkspaceNew         = "workspace_new"
	FeishuCommandWorkspaceNewDir      = "workspace_new_dir"
	FeishuCommandWorkspaceNewGit      = "workspace_new_git"
	FeishuCommandWorkspaceNewWorktree = "workspace_new_worktree"
	FeishuCommandWorkspaceDetach      = "workspace_detach"
	FeishuCommandAdmin                = "admin"
	FeishuCommandAdminSubcommand      = "admin_subcommand"
	FeishuCommandList                 = "list"
	FeishuCommandStatus               = "status"
	FeishuCommandUse                  = "use"
	FeishuCommandUseAll               = "useall"
	FeishuCommandNew                  = "new"
	FeishuCommandHistory              = "history"
	FeishuCommandSummary              = "summary"
	FeishuCommandReview               = "review"
	FeishuCommandSendFile             = "sendfile"
	FeishuCommandFollow               = "follow"
	FeishuCommandDetach               = "detach"
	FeishuCommandStop                 = "stop"
	FeishuCommandCompact              = "compact"
	FeishuCommandSteerAll             = "steerall"
	FeishuCommandMode                 = "mode"
	FeishuCommandAutoWhip             = "autowhip"
	FeishuCommandAutoContinue         = "autocontinue"
	FeishuCommandModel                = "model"
	FeishuCommandReasoning            = "reasoning"
	FeishuCommandAccess               = "access"
	FeishuCommandPlan                 = "plan"
	FeishuCommandVerbose              = "verbose"
	FeishuCommandCodexProvider        = "codex_provider"
	FeishuCommandClaudeProfile        = "claude_profile"
	FeishuCommandHelp                 = "help"
	FeishuCommandMenu                 = "menu"
	FeishuCommandDebug                = "debug"
	FeishuCommandCron                 = "cron"
	FeishuCommandUpgrade              = "upgrade"
	FeishuCommandPatch                = "patch"
	FeishuCommandVSCodeMigrate        = "vscode_migrate"
)
